name: TDEM_3D_examples

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - ipywidgets
  - mkl
  - pip
  - pip:
    - geoana==0.0.6
    - pymatsolver==0.1.2
    - discretize==0.4.11
    - SimPEG==0.13.1
